local coins = {
    coin = {
        name = 'Coin',
        imgHeads = love.graphics.newImage('assets/Flippers/Coins/Regular/CoinHeads.png'),
        imgTails = love.graphics.newImage('assets/Flippers/Coins/Regular/CoinTails.png'),
        imgFlipping = love.graphics.newImage('assets/Flippers/Coins/Regular/CoinFlipping.png'),
        frames = 3,
        frameWidth = nil,
        frameHeight = nil,
        bet = 1,
        betIncrement = 1,
        win = 2,
        lose = -1,
        winRate = 0.5,
    },
    luckycoin = {
        name = 'Lucky Coin',
        imgHeads = love.graphics.newImage('assets/Flippers/Coins/Lucky/LuckyCoinHeads.png'),
        imgTails = love.graphics.newImage('assets/Flippers/Coins/Lucky/LuckyCoinTails.png'),
        imgFlipping = love.graphics.newImage('assets/Flippers/Coins/Lucky/LuckyCoinFlipping.png'),
        frames = 3,
        frameWidth = nil,
        frameHeight = nil,
        bet = 2,
        betIncrement = 2,
        win = 2,
        lose = -2,
        winRate = 2/3,
    },
    unluckycoin = {
        name = 'Unlucky Coin',
        imgHeads = love.graphics.newImage('assets/Flippers/Coins/Unlucky/UnluckyCoinHeads.png'),
        imgTails = love.graphics.newImage('assets/Flippers/Coins/Unlucky/UnluckyCoinTails.png'),
        imgFlipping = love.graphics.newImage('assets/Flippers/Coins/Unlucky/UnluckyCoinFlipping.png'),
        frames = 3,
        frameWidth = nil,
        frameHeight = nil,
        bet = 1,
        betIncrement = 1,
        win = 2,
        lose = -1,
        winRate = 1/3,
    },
}
return coins 