local misc = {
    cat = {
        name = 'Cat',
        imgHeads = love.graphics.newImage('assets/Flippers/Misc/Cat/Cat.png'),
        imgTails = love.graphics.newImage('assets/Flippers/Misc/Cat/Cat.png'),
        imgFlipping = love.graphics.newImage('assets/Flippers/Misc/Cat/CatSpinClockwise.png'),
        frames = 4,
        frameWidth = nil,
        frameHeight = nil,
        bet = 3,
        betIncrement = 3,
        win = 1,
        lose = -3,
        winRate = 0.75,
    },
    grandma = {
        name = 'Grandma',
        imgHeads = love.graphics.newImage('assets/Flippers/Misc/Grandma/Grandma.png'),
        imgTails = love.graphics.newImage('assets/Flippers/Misc/Grandma/Grandma.png'),
        imgFlipping = love.graphics.newImage('assets/Flippers/Misc/Grandma/GrandmaClockwise.png'),
        frames = 4,
        frameWidth = nil,
        frameHeight = nil,
        bet = 1,
        betIncrement = 1,
        win = 8,
        lose = -1,
        winRate = 0.125,
    },
    toast = {
        name = 'Toast',
        imgHeads = love.graphics.newImage('assets/Flippers/Misc/Toast/ToastHeads.png'),
        imgTails = love.graphics.newImage('assets/Flippers/Misc/Toast/ToastTails.png'),
        imgFlipping = love.graphics.newImage('assets/Flippers/Misc/Toast/ToastClockwise.png'),
        frames = 8,
        frameWidth = nil,
        frameHeight = nil,
        bet = 1,
        betIncrement = 1,
        win = 8,
        lose = -1,
        winRate = 0.25,
    },
}
return misc 